type Species = {
  name: string;
  generatorUrl: string;
  defaultFemaleNames?: string[];
  defaultMaleNames?: string[];
  defaultNonBinaryNames?: string[];
};

const SPECIES: Species[] = [
  {
    name: "Alderaanian (Human)",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-alderaanian-names.php",
    defaultFemaleNames: [
      "suth ragas",
      "kila lublota",
      "hamidie storgirrann",
      "joyet kenn",
      "dreirloma glann",
      "vaye morlasiass",
      "dandri palvissurr",
      "orshe nylde",
      "cesto vadolliss",
      "drulodaa drylvagish",
    ],
    defaultMaleNames: [
      "sagrud kuss",
      "brant lodrirg",
      "naervosh gensotirm",
      "past glaldrogarm",
      "heezzull pardosh",
      "goll hus",
      "barlant grorgamint",
      "mendold pigrolesh",
      "krada tuss",
      "baihun turrano",
    ],
  },
  {
    name: "Anzati",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-anzati-names.php",
    defaultFemaleNames: [
      "kemmia sartuk",
      "sulle kintac",
      "feamme younriath",
      "fogo nealkkon",
      "filla mimror",
      "fogrea rannic",
      "codho meshih",
      "neli hecni",
      "bulo kethik",
      "rore rarrei",
    ],
    defaultMaleNames: [
      "dirku jinno",
      "gurtin neishac",
      "hekri musnah",
      "ismuk tecmik",
      "zimru jolkku",
      "zinrin yerta",
      "donro gimmur",
      "zerteth zittis",
      "sinnor valrik",
      "zaldik lasmus",
    ],
  },
  {
    name: "Aqualish",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-aqualish-names.php",
    defaultFemaleNames: [
      "zolftogth mangekati",
      "rifri araketa",
      "roshri skillergata",
      "cusdo skogiay",
      "inki preponbagg",
      "aldurna sun",
      "maimkisti tizix",
      "iaftanagth prewn",
      "cidana ulauwn",
      "kulfodri belmainbaggo",
    ],
    defaultMaleNames: [
      "tha torrun",
      "phoo spliraunmivvlu",
      "di fagzokruwwna",
      "wordek sceedauvvl",
      "molor halargeshi",
      "muazonk wih",
      "dekset vunte",
      "faveentat fer",
      "qedethench vantud",
      "purzira jet",
    ],
  },
  {
    name: "Arkanian",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-arkanian-names.php",
    defaultFemaleNames: [
      "borru odekdresh",
      "ormuze mendreltec",
      "kumu nurr",
      "yerraze ebish",
      "zondu zila",
      "gulri mund",
      "kathiza nand",
      "yalvawen ilting",
      "errinne zotac",
      "crande zur",
    ],
    defaultMaleNames: [
      "apre muln",
      "lerkic fith",
      "danril zerrond",
      "duric girr",
      "zaldrobel androzil",
      "dokdin rond",
      "gedrasia igreth",
      "nuldalo nod",
      "dygnisal buld",
      "noldiram virzengac",
    ],
  },
  {
    name: "Balosar",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-balosar-names.php",
    defaultFemaleNames: [
      "deeno legnivar",
      "dirreed zelli",
      "diggs ug'lavar",
      "tashagel vrezal",
      "naduth ondegnit",
      "fetid elarlan",
      "fasa luzat",
      "blilegid bur'dit",
      "zites ev'lus",
      "tame ug'lik",
    ],
    defaultMaleNames: [
      "grimo drol'melgor",
      "zilis vor'leggo",
      "zaargegs bril'mandis",
      "onter trilma",
      "fers vengi",
      "nerbor bamgu",
      "nilem vemduddad",
      "fins vag'li",
      "vols trel'ba",
      "bizzen melnul",
    ],
  },
  {
    name: "Besalisk",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-besalisk-names.php",
    defaultFemaleNames: [
      "nava zingrel",
      "choden ek",
      "thodal zil",
      "tegan vidrel",
      "thesan eg",
      "zess yettid",
      "foveh kriddig",
      "yozuin garvax",
      "has itror",
      "toren ed",
    ],
    defaultMaleNames: [
      "jeb gad",
      "dadris gindrill",
      "fob bektok",
      "goroul gral",
      "gol neg",
      "ken yengras",
      "belwer verag",
      "nas jalles",
      "boyke dadrall",
      "marreb atrad",
    ],
  },
  {
    name: "Bith",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-bith-names.php",
    defaultFemaleNames: [
      "mooshaa r'halo",
      "humlu k'sass",
      "theuhool gin",
      "fobeu molu",
      "rebooh gire",
      "lommi thanress",
      "phaammen rhonas",
      "pheunam g'homarn",
      "rugrialno k'sasiss",
      "fimnemloom d'urorn",
    ],
    defaultMaleNames: [
      "g'hiaddens ras",
      "diamew hus",
      "daamko jim",
      "g'henool g'hese",
      "gidul fim",
      "g'hulloss phudu",
      "f'teupe k'susis",
      "f'tolkeuss gorder",
      "phuzeku phulra",
      "rimecro numnu",
    ],
  },
  {
    name: "Bothan",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-bothan-names.php",
    defaultFemaleNames: [
      "dhul faqias",
      "thath gundais",
      "vaenn diaqeva",
      "al nasiv",
      "thaar dorrot",
      "lann kilev",
      "yum krandiri",
      "otraenn dondem",
      "dhasar doqan",
      "thintis niheho",
    ],
    defaultMaleNames: [
      "hiath foh'raha",
      "trum nonduto",
      "vik litheme",
      "him sa'lal",
      "ec kra'rel",
      "grusc grendute",
      "doth ninov",
      "cikog bwen'nor",
      "gihir ha'fase",
      "griduc verire",
    ],
  },
  {
    name: "Cerean",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-cerean-names.php",
    defaultFemaleNames: [
      "nim chris",
      "hyn adel",
      "jys zirramis",
      "bymn cuncondurr",
      "oelre colindix",
      "zidhe nidolir",
      "rhoecheth nindeltreir",
      "sylevy immux",
      "zafveny famoltror",
      "noafvylvi lun",
    ],
    defaultMaleNames: [
      "hu-Za-Ynmom zolledil",
      "burduth-Tcharud-Mynz kammux",
      "kars-Wendudd-Hoorim cendax",
      "dors-Zywi-Rorfunn myirr",
      "perfodd-Chenmi benennur",
      "dath-Byrs chru",
      "jadi-Mad-Ena gift",
      "le girrur",
      "fefla-Honz boseille",
      "hundurs-Skirfonz gareft",
    ],
  },
  {
    name: "Chalactan",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-chalactan-names.php",
    defaultFemaleNames: [
      "turrins bhembo",
      "drer duchalik",
      "vargels edrak",
      "restudh ahuttel",
      "paadh jevor",
      "eela chede",
      "chals kinyu",
      "sholems tokshi",
      "ota hikre",
      "krathal dhushte",
    ],
    defaultMaleNames: [
      "pomov vapibu",
      "hishel bashteyo",
      "aadand mundap",
      "rohan bepala",
      "harjup ugeno",
      "lendet sadhu",
      "rahet pihukej",
      "jibho tonnar",
      "uzal urad",
      "rayu turaso",
    ],
  },
  {
    name: "Chandrilan (Human)",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-chandrilan-names.php",
    defaultFemaleNames: [
      "eidon dybol",
      "ler ylwile",
      "sollin adrashist",
      "jies redeusha",
      "pieh ros",
      "ome feirk",
      "tuctih bagad",
      "amie osesho",
      "por gilwoced",
      "allan effid",
    ],
    defaultMaleNames: [
      "moldo trinteulend",
      "zuhl geilellirk",
      "zatham zothmaanest",
      "kaog omir",
      "mid badresser",
      "saellembeg zark",
      "daldush freedrald",
      "githruux lyldaal",
      "zurdo eisark",
      "suwi caiglile",
    ],
  },
  {
    name: "Clawdite",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-clawdite-names.php",
    defaultFemaleNames: [
      "nas sennan",
      "kram wimall",
      "pron ranid",
      "pran sal",
      "raksam del",
      "bivux pikam",
      "gagtud nad",
      "cinom mal",
      "cingom sak",
      "rigtex sen",
    ],
    defaultMaleNames: [
      "dim blekir",
      "zon wezum",
      "nussek",
      "pien lak",
      "turlais gullac",
      "vulmid rortom",
      "milles mir",
      "turvot bohzyll",
      "nenniem mir",
      "lurlod ryzac",
    ],
  },
  {
    name: "Clone",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-clone-names.php",
    defaultMaleNames: [
      "jass",
      " seerrt",
      " xuppynks",
      " beppam",
      " dural",
      " hippick",
      " Dream",
      " CT-678-4408",
      " MT628",
      " UG776",
    ],
  },
  {
    name: "Codru-Ji",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-codru-ji-names.php",
    defaultFemaleNames: [
      "reina",
      "men",
      "yet",
      "nadda",
      "fera",
      "yet",
      "tiyi",
      "san",
      "nose",
      "henno",
    ],
    defaultMaleNames: [
      "vrurl",
      "rilm",
      "kam",
      "iqa",
      "brarroc",
      "jaggud",
      "graggo",
      "gikirl",
      "duggir",
      "uqa",
    ],
  },
  {
    name: "Corellian (Human)",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-corellian-names.php",
    defaultFemaleNames: [
      "fage orvers",
      "kissiw shidgem",
      "cassaw staldro",
      "vyndryl fedda",
      "hes tistre",
      "phas garkoonnal",
      "ruli oonchim",
      "davally ontek",
      "phedre crarbarak",
      "haw ierkoss",
    ],
    defaultMaleNames: [
      "threm jor",
      "pish rihom",
      "borshusash emen",
      "brit thryldill",
      "peic ierveb",
      "fotti ferchon",
      "chesh heenva",
      "geek sirkoak",
      "abbid arkar",
      "peirvec zers",
    ],
  },
  {
    name: "Coruscanti (Human)",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-coruscanti-names.php",
    defaultFemaleNames: [
      "ihini mas",
      "airlin roli",
      "ime trallirr",
      "aoltime maudi",
      "shass tiegill",
      "sidnesti fateng",
      "isille nung",
      "ghegy vierza",
      "shier vydill",
      "tara lielleshol",
    ],
    defaultMaleNames: [
      "rik imma",
      "heak fald",
      "luq jotold",
      "otan lammith",
      "religenn vienn",
      "nannon breeslill",
      "shirdock polong",
      "geallitek brann",
      "unad naum",
      "mar leimo",
    ],
  },
  {
    name: "Dathomirian",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-dathomirian-names.php",
    defaultFemaleNames: [
      "ran itro",
      "theg noggraj",
      "trav nunta",
      "chinzad ozraz",
      "unzij zidaz",
      "trulzig ronra",
      "shelna junrosh",
      "sherjachann djuvvo",
      "zechuasia ozel",
      "tihvanaz vellot",
    ],
    defaultMaleNames: [
      "Hell djoda",
      "Hysterical gagroq",
      "Merciless yeldal",
      "Nefarious ave",
      "Damned rode",
      "Aberrant kokroq",
      "Riot chepriq",
      "Odious djeldass",
      "Hellion chaggra",
      "Aberrant nadrizz",
    ],
  },
  {
    name: "Devaronian",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-devaronian-names.php",
    defaultFemaleNames: [
      "ghu gar",
      "hu t'rumrask",
      "vos t'rokt",
      "sun grekrir",
      "tisen huhrk",
      "nemmon brossal",
      "lenchun braq",
      "kubhi cosnaact",
      "nessedhis dhahk",
      "mimemnim jusandt",
    ],
    defaultMaleNames: [
      "vrult cuct",
      "varc cexiq",
      "lec brel",
      "gehr graallandt",
      "zecalc dhuw",
      "greirtahk n'vokuv",
      "vurtu d'vind",
      "solihk nimrihrk",
      "sakevrox vuq",
      "guelmilmak d'vimnondt",
    ],
  },
  {
    name: "Dug",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-dug-names.php",
    defaultNonBinaryNames: [
      "paakei lterdoudi",
      "bogruhx ndornad",
      "bigwed brakwos",
      "volnux ndodeda",
      "sakhu bosude",
      "baalwagwi ddinsain",
      "sokingu gnaawor",
      "dogwenbe lbaiwen",
      "juwedda lwisen",
      "gegedi gwekodi",
    ],
  },
  {
    name: "Duros",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-duros-names.php",
    defaultFemaleNames: [
      "dachu zhelt",
      "jena lilmig",
      "telu jis",
      "neslu stirril",
      "dilo zham",
      "haina tromde",
      "zinnidwi til",
      "jeinadei babil",
      "zuslarlu lo",
      "zaduda mogu",
    ],
    defaultMaleNames: [
      "ren jis",
      "cod banal",
      "can mig",
      "nir kaggid",
      "homar leg",
      "gulzim hunteks",
      "dilam veg",
      "hodim sabbe",
      "malwelwum tug",
      "limunsom duntum",
    ],
  },
  {
    name: "Ewok",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-ewok-names.php",
    defaultFemaleNames: [
      "nasta neenic",
      "kake glaliddi",
      "pegle zadrec",
      "berraa kanemra",
      "narree jilran",
      "rera gligrari",
      "paprarphi laakkyng",
      "desirpi krirentoo",
      "neloosti grakool",
      "kinakoo meedraka",
    ],
    defaultMaleNames: [
      "elan rimnet",
      "dimel greddilre",
      "iba gleereem",
      "nelleng benrekke",
      "piby dadral",
      "tidreck darerra",
      "wirfoo zaagril",
      "gidim bikika",
      "dide glilic",
      "greedrit daakarroo",
    ],
  },
  {
    name: "Falleen",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-falleen-names.php",
    defaultFemaleNames: [
      "zel sit",
      "nel bruthruss",
      "dus brum",
      "em tonsor",
      "kruut breem",
      "genleel mammic",
      "semmun zic",
      "ivo wuvror",
      "divobs taj",
      "sife xusvoj",
    ],
    defaultMaleNames: [
      "czet brir",
      "czan zennum",
      "keest wuuc",
      "thux suunseem",
      "treer mic",
      "hoszinn zonren",
      "sunos zom",
      "tazzax xeegol",
      "siszun krur",
      "kazu disuux",
    ],
  },
  {
    name: "Farghul",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-farghul-names.php",
    defaultFemaleNames: [
      "aasi",
      "dasole",
      "dezo",
      "lode",
      "rezaya",
      "nemana",
      "yiko",
      "milaye",
      "hona",
      "brakiya",
    ],
    defaultMaleNames: [
      "tallat",
      "muzirll",
      "nulalg",
      "nets",
      "zug",
      "mollot",
      "hoshap",
      "nots",
      "zanchol",
      "med",
    ],
  },
  {
    name: "Gamorrean",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-gamorrean-names.php",
    defaultFemaleNames: [
      "uuvnern peng",
      "rekmin koodvaks",
      "zeekmiff riss",
      "pauggeacz rolnougg",
      "oggoff ock",
      "ragneng brumreerrp",
      "grothnuc geulk",
      "bligsho rozzoks",
      "kenthang puas",
      "muutrot holroork",
    ],
    defaultMaleNames: [
      "vrirp bof",
      "xoot drooshurth",
      "eac grracz",
      "treg jougins",
      "bnerc gigg",
      "allirn stiggtusz",
      "nubnirp kuunn",
      "naubnokk slelgoorrt",
      "calon scurp",
      "trefnugh trurkos",
    ],
  },
  {
    name: "Gand",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-gand-names.php",
    defaultNonBinaryNames: [
      "nyik lurna",
      "rik neyffyu",
      "il trizuu",
      "tyush quqoo",
      "yan pryizzo",
      "suuffass drothay",
      "ninlen trizlaa",
      "uzaar cnozlo",
      "s'zulden pryicly",
      "ukoor nezlyu",
    ],
  },
  {
    name: "Gen'dai",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-gendai-names.php",
    defaultNonBinaryNames: [
      "relne",
      "amdron",
      "relgrome",
      "reldralatt",
      "vagros",
      "momdruze",
      "vundaz",
      "ogru",
      "gesto",
      "zalnan",
    ],
  },
  {
    name: "Geonosian",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-geonosian-names.php",
    defaultFemaleNames: [
      "runi chalkok",
      "tele sinpes",
      "kade neddat",
      "yaze raggek",
      "leme mokkak",
      "zamesha rel",
      "melinne fit",
      "motere mompa",
      "sahasso madde",
      "limasi fak",
    ],
    defaultMaleNames: [
      "bizz chamna",
      "nek mac",
      "ness chenkel",
      "ten horles",
      "gygg nirli",
      "ezuck moddut",
      "urgey larpet",
      "tale zuk",
      "hikruss zok",
      "nukrigg hommad",
    ],
  },
  {
    name: "Gotal",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-gotal-names.php",
    defaultMaleNames: [
      "jun krogg",
      "saur trohsark",
      "tutt gern",
      "furn nothit",
      "tuth negh",
      "mekuush jiskonth",
      "jeshnom nan",
      "fat'neett kushux",
      "nexzeex kanth",
      "gloxzaul grerloth",
    ],
  },
  {
    name: "Gran",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-gran-names.php",
    defaultFemaleNames: [
      "vewz groer",
      "breks driekiaj",
      "ge sheez",
      "cak peekeeks",
      "ti rhoex",
      "yeperg beaghog",
      "messoyk driand",
      "zunnuks joetoth",
      "phuksawz yoeg",
      "coskorg drieneb",
    ],
    defaultMaleNames: [
      "ad yoeps",
      "ki dreico",
      "grund klaas",
      "jok kheikkeb",
      "yerch kroed",
      "rebuth kroeyig",
      "tiwha aass",
      "perroj yaarli",
      "broggiff feess",
      "figgieg klietiyk",
    ],
  },
  {
    name: "Gungan",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-gungan-names.php",
    defaultFemaleNames: [
      "fle trad",
      "kho porud",
      "blof moth",
      "bo bapfa",
      "tha-tha shaz",
      "e-e sleful",
      "bee-bee grent",
      "tinbod hoekkewn",
      "duewers kaz",
      "yumbo qiarsaz",
    ],
    defaultMaleNames: [
      "ski poent",
      "skah slilsiezz",
      "kror rurr",
      "blief grakkoenks",
      "bert-bert squnt",
      "froef-froef shullown",
      "paff-paff shels",
      "wakfec grifa",
      "crebbass tril",
      "naubboow trondierr",
    ],
  },
  {
    name: "Hutt",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-hutt-names.php",
    defaultNonBinaryNames: [
      "niddlo tenjed",
      "mambu gish",
      "sawnu sparloz",
      "gerka fihl",
      "braddlish smashain",
      "bwono bard",
      "tillob yachre",
      "giffiwu praiz",
      "shegrishell kastib",
      "boojaabug proh",
    ],
  },
  {
    name: "Iktotchi",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-iktotchi-names.php",
    defaultFemaleNames: [
      "tumkij vemin",
      "zishi dis",
      "torne vehaan",
      "furur tar",
      "tifna chizu",
      "farli kaal",
      "nunkon haadamm",
      "kifloj zemm",
      "caron chafel",
      "comnon vos",
    ],
    defaultMaleNames: [
      "niflaer hedimm",
      "seldam namm",
      "halde defas",
      "cilva chal",
      "nofur toda",
      "dumraej du",
      "zulmon kejiin",
      "wushkeij kiir",
      "canvij nafas",
      "mifyi jimm",
    ],
  },
  {
    name: "Ishi Tib",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-ishi-tib-names.php",
    defaultFemaleNames: [
      "onzas hul",
      "sihre drambow",
      "voprem lin",
      "iklyen anduc",
      "pholga baw",
      "almof drargim",
      "enlianter zil",
      "seghesmim laebirr",
      "emziekhon brutz",
      "hineffeth draelziff",
    ],
    defaultMaleNames: [
      "shel tun",
      "ciam slaalraal",
      "shech letz",
      "tund zimzaff",
      "rumluch nong",
      "tagrog tikzuw",
      "jubleet ruff",
      "shartemrind vunre",
      "shurnanrurc cael",
      "henlomich vorgom",
    ],
  },
  {
    name: "Ithorian",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-ithorian-names.php",
    defaultFemaleNames: [
      "vle sokill",
      "ma slowowethh",
      "vhees chooso",
      "khys tat",
      "bhywshyl eblum",
      "cwohhamm sitrohol",
      "pwiwhah dirtan",
      "kluuwlyrmaf noolendi",
      "nenforher frootim",
      "swydwalsoh lurlq",
    ],
    defaultMaleNames: [
      "je tofe",
      "leth viweddod",
      "qerr pwaqed",
      "dac frill",
      "houxxurr buflig",
      "feemfarn indebblok",
      "onciwl verek",
      "libbumfew nivulirlq",
      "jwissomleerd turid",
      "phuuwbonuut lits",
    ],
  },
  {
    name: "Jawa",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-jawa-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Kaleesh",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-kaleesh-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Kaminoan",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-kaminoan-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Kel Dor",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-kel-dor-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Keshiri",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-keshiri-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Kiffar",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-kiffar-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Klatooinian",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-klatooinian-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Korunnai",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-korunnai-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Kowakian Monkey-Lizard",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-kowakian-monkey-lizard-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Kubaz",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-kubaz-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Lasat",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-lasat-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Lothalite",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-lothalite-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Mandalorian",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-mandalorian-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Mikkian",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-mikkian-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Mirialan",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-mirialan-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Mon Calamari",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-mon-calamari-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Muun",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-muun-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Naboo",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-naboo-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Nautolan",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-nautolan-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Neimoidian",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-neimoidian-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Nikto",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-nikto-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Nothoiin",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-nothoiin-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Onderonian",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-onderonian-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Ortolan",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-ortolan-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Pantoran",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-pantoran-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Pau'an",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-pauan-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Planet",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-planet-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Quarren",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-quarren-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Rodian",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-rodian-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Savarian",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-savarian-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Selkath",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-selkath-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Selonian",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-selonian-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Sephi",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-sephi-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Serennian",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-serennian-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Shistavanen",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-shistavanen-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Skakoan",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-skakoan-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Snivvian",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-snivvian-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Stormtrooper",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-stormtrooper-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Sullustan",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-sullustan-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Talz",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-talz-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Tholothian",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-tholothian-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Togruta",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-togruta-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Toydarian",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-toydarian-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Trandoshan",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-trandoshan-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Tusken Raider",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-tusken-raider-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Twi'lek",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-twilek-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Ugnaughts",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-ugnaught-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Weequay",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-weequay-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Wookiee",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-wookiee-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Yarkora",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-yarkora-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Zabrak",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-zabrak-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Zeltron",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-zeltron-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
  {
    name: "Zygerrian",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-zygerrian-names.php",
    defaultFemaleNames: [],
    defaultMaleNames: [],
  },
];

const NUM_SPECIES = SPECIES.length;

export { SPECIES, NUM_SPECIES };
