type Species = {
  /**
   * The name of the species.
   */
  name: string;
  /**
   * A link to a random generator for the species.
   */
  generatorUrl: string;
  /**
   * A list of female names for the species (if they exist).
   */
  defaultFemaleNames?: string[];
  /**
   * A list of male names for the species (if they exist).
   */
  defaultMaleNames?: string[];
  /**
   * A list of non-binary names for the species (if they exist).
   */
  defaultNonBinaryNames?: string[];
};

const SPECIES: { [key: string]: Species } = {
  "Alderaanian (Human)": {
    name: "Alderaanian (Human)",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-alderaanian-names.php",
    defaultFemaleNames: [
      "suth ragas",
      "kila lublota",
      "hamidie storgirrann",
      "joyet kenn",
      "dreirloma glann",
      "vaye morlasiass",
      "dandri palvissurr",
      "orshe nylde",
      "cesto vadolliss",
      "drulodaa drylvagish",
    ],
    defaultMaleNames: [
      "sagrud kuss",
      "brant lodrirg",
      "naervosh gensotirm",
      "past glaldrogarm",
      "heezzull pardosh",
      "goll hus",
      "barlant grorgamint",
      "mendold pigrolesh",
      "krada tuss",
      "baihun turrano",
    ],
  },
  Anzati: {
    name: "Anzati",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-anzati-names.php",
    defaultFemaleNames: [
      "kemmia sartuk",
      "sulle kintac",
      "feamme younriath",
      "fogo nealkkon",
      "filla mimror",
      "fogrea rannic",
      "codho meshih",
      "neli hecni",
      "bulo kethik",
      "rore rarrei",
    ],
    defaultMaleNames: [
      "dirku jinno",
      "gurtin neishac",
      "hekri musnah",
      "ismuk tecmik",
      "zimru jolkku",
      "zinrin yerta",
      "donro gimmur",
      "zerteth zittis",
      "sinnor valrik",
      "zaldik lasmus",
    ],
  },
  Aqualish: {
    name: "Aqualish",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-aqualish-names.php",
    defaultFemaleNames: [
      "zolftogth mangekati",
      "rifri araketa",
      "roshri skillergata",
      "cusdo skogiay",
      "inki preponbagg",
      "aldurna sun",
      "maimkisti tizix",
      "iaftanagth prewn",
      "cidana ulauwn",
      "kulfodri belmainbaggo",
    ],
    defaultMaleNames: [
      "tha torrun",
      "phoo spliraunmivvlu",
      "di fagzokruwwna",
      "wordek sceedauvvl",
      "molor halargeshi",
      "muazonk wih",
      "dekset vunte",
      "faveentat fer",
      "qedethench vantud",
      "purzira jet",
    ],
  },
  Arkanian: {
    name: "Arkanian",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-arkanian-names.php",
    defaultFemaleNames: [
      "borru odekdresh",
      "ormuze mendreltec",
      "kumu nurr",
      "yerraze ebish",
      "zondu zila",
      "gulri mund",
      "kathiza nand",
      "yalvawen ilting",
      "errinne zotac",
      "crande zur",
    ],
    defaultMaleNames: [
      "apre muln",
      "lerkic fith",
      "danril zerrond",
      "duric girr",
      "zaldrobel androzil",
      "dokdin rond",
      "gedrasia igreth",
      "nuldalo nod",
      "dygnisal buld",
      "noldiram virzengac",
    ],
  },
  Balosar: {
    name: "Balosar",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-balosar-names.php",
    defaultFemaleNames: [
      "deeno legnivar",
      "dirreed zelli",
      "diggs ug'lavar",
      "tashagel vrezal",
      "naduth ondegnit",
      "fetid elarlan",
      "fasa luzat",
      "blilegid bur'dit",
      "zites ev'lus",
      "tame ug'lik",
    ],
    defaultMaleNames: [
      "grimo drol'melgor",
      "zilis vor'leggo",
      "zaargegs bril'mandis",
      "onter trilma",
      "fers vengi",
      "nerbor bamgu",
      "nilem vemduddad",
      "fins vag'li",
      "vols trel'ba",
      "bizzen melnul",
    ],
  },
  Besalisk: {
    name: "Besalisk",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-besalisk-names.php",
    defaultFemaleNames: [
      "nava zingrel",
      "choden ek",
      "thodal zil",
      "tegan vidrel",
      "thesan eg",
      "zess yettid",
      "foveh kriddig",
      "yozuin garvax",
      "has itror",
      "toren ed",
    ],
    defaultMaleNames: [
      "jeb gad",
      "dadris gindrill",
      "fob bektok",
      "goroul gral",
      "gol neg",
      "ken yengras",
      "belwer verag",
      "nas jalles",
      "boyke dadrall",
      "marreb atrad",
    ],
  },
  Bith: {
    name: "Bith",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-bith-names.php",
    defaultFemaleNames: [
      "mooshaa r'halo",
      "humlu k'sass",
      "theuhool gin",
      "fobeu molu",
      "rebooh gire",
      "lommi thanress",
      "phaammen rhonas",
      "pheunam g'homarn",
      "rugrialno k'sasiss",
      "fimnemloom d'urorn",
    ],
    defaultMaleNames: [
      "g'hiaddens ras",
      "diamew hus",
      "daamko jim",
      "g'henool g'hese",
      "gidul fim",
      "g'hulloss phudu",
      "f'teupe k'susis",
      "f'tolkeuss gorder",
      "phuzeku phulra",
      "rimecro numnu",
    ],
  },
  Bothan: {
    name: "Bothan",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-bothan-names.php",
    defaultFemaleNames: [
      "dhul faqias",
      "thath gundais",
      "vaenn diaqeva",
      "al nasiv",
      "thaar dorrot",
      "lann kilev",
      "yum krandiri",
      "otraenn dondem",
      "dhasar doqan",
      "thintis niheho",
    ],
    defaultMaleNames: [
      "hiath foh'raha",
      "trum nonduto",
      "vik litheme",
      "him sa'lal",
      "ec kra'rel",
      "grusc grendute",
      "doth ninov",
      "cikog bwen'nor",
      "gihir ha'fase",
      "griduc verire",
    ],
  },
  Cerean: {
    name: "Cerean",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-cerean-names.php",
    defaultFemaleNames: [
      "nim chris",
      "hyn adel",
      "jys zirramis",
      "bymn cuncondurr",
      "oelre colindix",
      "zidhe nidolir",
      "rhoecheth nindeltreir",
      "sylevy immux",
      "zafveny famoltror",
      "noafvylvi lun",
    ],
    defaultMaleNames: [
      "hu-Za-Ynmom zolledil",
      "burduth-Tcharud-Mynz kammux",
      "kars-Wendudd-Hoorim cendax",
      "dors-Zywi-Rorfunn myirr",
      "perfodd-Chenmi benennur",
      "dath-Byrs chru",
      "jadi-Mad-Ena gift",
      "le girrur",
      "fefla-Honz boseille",
      "hundurs-Skirfonz gareft",
    ],
  },
  Chalactan: {
    name: "Chalactan",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-chalactan-names.php",
    defaultFemaleNames: [
      "turrins bhembo",
      "drer duchalik",
      "vargels edrak",
      "restudh ahuttel",
      "paadh jevor",
      "eela chede",
      "chals kinyu",
      "sholems tokshi",
      "ota hikre",
      "krathal dhushte",
    ],
    defaultMaleNames: [
      "pomov vapibu",
      "hishel bashteyo",
      "aadand mundap",
      "rohan bepala",
      "harjup ugeno",
      "lendet sadhu",
      "rahet pihukej",
      "jibho tonnar",
      "uzal urad",
      "rayu turaso",
    ],
  },
  "Chandrilan (Human)": {
    name: "Chandrilan (Human)",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-chandrilan-names.php",
    defaultFemaleNames: [
      "eidon dybol",
      "ler ylwile",
      "sollin adrashist",
      "jies redeusha",
      "pieh ros",
      "ome feirk",
      "tuctih bagad",
      "amie osesho",
      "por gilwoced",
      "allan effid",
    ],
    defaultMaleNames: [
      "moldo trinteulend",
      "zuhl geilellirk",
      "zatham zothmaanest",
      "kaog omir",
      "mid badresser",
      "saellembeg zark",
      "daldush freedrald",
      "githruux lyldaal",
      "zurdo eisark",
      "suwi caiglile",
    ],
  },
  Clawdite: {
    name: "Clawdite",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-clawdite-names.php",
    defaultFemaleNames: [
      "nas sennan",
      "kram wimall",
      "pron ranid",
      "pran sal",
      "raksam del",
      "bivux pikam",
      "gagtud nad",
      "cinom mal",
      "cingom sak",
      "rigtex sen",
    ],
    defaultMaleNames: [
      "dim blekir",
      "zon wezum",
      "nussek",
      "pien lak",
      "turlais gullac",
      "vulmid rortom",
      "milles mir",
      "turvot bohzyll",
      "nenniem mir",
      "lurlod ryzac",
    ],
  },
  Clone: {
    name: "Clone",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-clone-names.php",
    defaultMaleNames: [
      "jass",
      " seerrt",
      " xuppynks",
      " beppam",
      " dural",
      " hippick",
      " Dream",
      " CT-678-4408",
      " MT628",
      " UG776",
    ],
  },
  "Codru-Ji": {
    name: "Codru-Ji",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-codru-ji-names.php",
    defaultFemaleNames: [
      "reina",
      "men",
      "yet",
      "nadda",
      "fera",
      "yet",
      "tiyi",
      "san",
      "nose",
      "henno",
    ],
    defaultMaleNames: [
      "vrurl",
      "rilm",
      "kam",
      "iqa",
      "brarroc",
      "jaggud",
      "graggo",
      "gikirl",
      "duggir",
      "uqa",
    ],
  },
  "Corellian (Human)": {
    name: "Corellian (Human)",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-corellian-names.php",
    defaultFemaleNames: [
      "fage orvers",
      "kissiw shidgem",
      "cassaw staldro",
      "vyndryl fedda",
      "hes tistre",
      "phas garkoonnal",
      "ruli oonchim",
      "davally ontek",
      "phedre crarbarak",
      "haw ierkoss",
    ],
    defaultMaleNames: [
      "threm jor",
      "pish rihom",
      "borshusash emen",
      "brit thryldill",
      "peic ierveb",
      "fotti ferchon",
      "chesh heenva",
      "geek sirkoak",
      "abbid arkar",
      "peirvec zers",
    ],
  },
  "Coruscanti (Human)": {
    name: "Coruscanti (Human)",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-coruscanti-names.php",
    defaultFemaleNames: [
      "ihini mas",
      "airlin roli",
      "ime trallirr",
      "aoltime maudi",
      "shass tiegill",
      "sidnesti fateng",
      "isille nung",
      "ghegy vierza",
      "shier vydill",
      "tara lielleshol",
    ],
    defaultMaleNames: [
      "rik imma",
      "heak fald",
      "luq jotold",
      "otan lammith",
      "religenn vienn",
      "nannon breeslill",
      "shirdock polong",
      "geallitek brann",
      "unad naum",
      "mar leimo",
    ],
  },
  Dathomirian: {
    name: "Dathomirian",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-dathomirian-names.php",
    defaultFemaleNames: [
      "ran itro",
      "theg noggraj",
      "trav nunta",
      "chinzad ozraz",
      "unzij zidaz",
      "trulzig ronra",
      "shelna junrosh",
      "sherjachann djuvvo",
      "zechuasia ozel",
      "tihvanaz vellot",
    ],
    defaultMaleNames: [
      "Hell djoda",
      "Hysterical gagroq",
      "Merciless yeldal",
      "Nefarious ave",
      "Damned rode",
      "Aberrant kokroq",
      "Riot chepriq",
      "Odious djeldass",
      "Hellion chaggra",
      "Aberrant nadrizz",
    ],
  },
  Devaronian: {
    name: "Devaronian",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-devaronian-names.php",
    defaultFemaleNames: [
      "ghu gar",
      "hu t'rumrask",
      "vos t'rokt",
      "sun grekrir",
      "tisen huhrk",
      "nemmon brossal",
      "lenchun braq",
      "kubhi cosnaact",
      "nessedhis dhahk",
      "mimemnim jusandt",
    ],
    defaultMaleNames: [
      "vrult cuct",
      "varc cexiq",
      "lec brel",
      "gehr graallandt",
      "zecalc dhuw",
      "greirtahk n'vokuv",
      "vurtu d'vind",
      "solihk nimrihrk",
      "sakevrox vuq",
      "guelmilmak d'vimnondt",
    ],
  },
  Dug: {
    name: "Dug",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-dug-names.php",
    defaultNonBinaryNames: [
      "paakei lterdoudi",
      "bogruhx ndornad",
      "bigwed brakwos",
      "volnux ndodeda",
      "sakhu bosude",
      "baalwagwi ddinsain",
      "sokingu gnaawor",
      "dogwenbe lbaiwen",
      "juwedda lwisen",
      "gegedi gwekodi",
    ],
  },
  Duros: {
    name: "Duros",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-duros-names.php",
    defaultFemaleNames: [
      "dachu zhelt",
      "jena lilmig",
      "telu jis",
      "neslu stirril",
      "dilo zham",
      "haina tromde",
      "zinnidwi til",
      "jeinadei babil",
      "zuslarlu lo",
      "zaduda mogu",
    ],
    defaultMaleNames: [
      "ren jis",
      "cod banal",
      "can mig",
      "nir kaggid",
      "homar leg",
      "gulzim hunteks",
      "dilam veg",
      "hodim sabbe",
      "malwelwum tug",
      "limunsom duntum",
    ],
  },
  Ewok: {
    name: "Ewok",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-ewok-names.php",
    defaultFemaleNames: [
      "nasta neenic",
      "kake glaliddi",
      "pegle zadrec",
      "berraa kanemra",
      "narree jilran",
      "rera gligrari",
      "paprarphi laakkyng",
      "desirpi krirentoo",
      "neloosti grakool",
      "kinakoo meedraka",
    ],
    defaultMaleNames: [
      "elan rimnet",
      "dimel greddilre",
      "iba gleereem",
      "nelleng benrekke",
      "piby dadral",
      "tidreck darerra",
      "wirfoo zaagril",
      "gidim bikika",
      "dide glilic",
      "greedrit daakarroo",
    ],
  },
  Falleen: {
    name: "Falleen",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-falleen-names.php",
    defaultFemaleNames: [
      "zel sit",
      "nel bruthruss",
      "dus brum",
      "em tonsor",
      "kruut breem",
      "genleel mammic",
      "semmun zic",
      "ivo wuvror",
      "divobs taj",
      "sife xusvoj",
    ],
    defaultMaleNames: [
      "czet brir",
      "czan zennum",
      "keest wuuc",
      "thux suunseem",
      "treer mic",
      "hoszinn zonren",
      "sunos zom",
      "tazzax xeegol",
      "siszun krur",
      "kazu disuux",
    ],
  },
  Farghul: {
    name: "Farghul",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-farghul-names.php",
    defaultFemaleNames: [
      "aasi",
      "dasole",
      "dezo",
      "lode",
      "rezaya",
      "nemana",
      "yiko",
      "milaye",
      "hona",
      "brakiya",
    ],
    defaultMaleNames: [
      "tallat",
      "muzirll",
      "nulalg",
      "nets",
      "zug",
      "mollot",
      "hoshap",
      "nots",
      "zanchol",
      "med",
    ],
  },
  Gamorrean: {
    name: "Gamorrean",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-gamorrean-names.php",
    defaultFemaleNames: [
      "uuvnern peng",
      "rekmin koodvaks",
      "zeekmiff riss",
      "pauggeacz rolnougg",
      "oggoff ock",
      "ragneng brumreerrp",
      "grothnuc geulk",
      "bligsho rozzoks",
      "kenthang puas",
      "muutrot holroork",
    ],
    defaultMaleNames: [
      "vrirp bof",
      "xoot drooshurth",
      "eac grracz",
      "treg jougins",
      "bnerc gigg",
      "allirn stiggtusz",
      "nubnirp kuunn",
      "naubnokk slelgoorrt",
      "calon scurp",
      "trefnugh trurkos",
    ],
  },
  Gand: {
    name: "Gand",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-gand-names.php",
    defaultNonBinaryNames: [
      "nyik lurna",
      "rik neyffyu",
      "il trizuu",
      "tyush quqoo",
      "yan pryizzo",
      "suuffass drothay",
      "ninlen trizlaa",
      "uzaar cnozlo",
      "s'zulden pryicly",
      "ukoor nezlyu",
    ],
  },
  "Gen'dai": {
    name: "Gen'dai",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-gendai-names.php",
    defaultNonBinaryNames: [
      "relne",
      "amdron",
      "relgrome",
      "reldralatt",
      "vagros",
      "momdruze",
      "vundaz",
      "ogru",
      "gesto",
      "zalnan",
    ],
  },
  Geonosian: {
    name: "Geonosian",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-geonosian-names.php",
    defaultFemaleNames: [
      "runi chalkok",
      "tele sinpes",
      "kade neddat",
      "yaze raggek",
      "leme mokkak",
      "zamesha rel",
      "melinne fit",
      "motere mompa",
      "sahasso madde",
      "limasi fak",
    ],
    defaultMaleNames: [
      "bizz chamna",
      "nek mac",
      "ness chenkel",
      "ten horles",
      "gygg nirli",
      "ezuck moddut",
      "urgey larpet",
      "tale zuk",
      "hikruss zok",
      "nukrigg hommad",
    ],
  },
  Gotal: {
    name: "Gotal",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-gotal-names.php",
    defaultMaleNames: [
      "jun krogg",
      "saur trohsark",
      "tutt gern",
      "furn nothit",
      "tuth negh",
      "mekuush jiskonth",
      "jeshnom nan",
      "fat'neett kushux",
      "nexzeex kanth",
      "gloxzaul grerloth",
    ],
  },
  Gran: {
    name: "Gran",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-gran-names.php",
    defaultFemaleNames: [
      "vewz groer",
      "breks driekiaj",
      "ge sheez",
      "cak peekeeks",
      "ti rhoex",
      "yeperg beaghog",
      "messoyk driand",
      "zunnuks joetoth",
      "phuksawz yoeg",
      "coskorg drieneb",
    ],
    defaultMaleNames: [
      "ad yoeps",
      "ki dreico",
      "grund klaas",
      "jok kheikkeb",
      "yerch kroed",
      "rebuth kroeyig",
      "tiwha aass",
      "perroj yaarli",
      "broggiff feess",
      "figgieg klietiyk",
    ],
  },
  Gungan: {
    name: "Gungan",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-gungan-names.php",
    defaultFemaleNames: [
      "fle trad",
      "kho porud",
      "blof moth",
      "bo bapfa",
      "tha-tha shaz",
      "e-e sleful",
      "bee-bee grent",
      "tinbod hoekkewn",
      "duewers kaz",
      "yumbo qiarsaz",
    ],
    defaultMaleNames: [
      "ski poent",
      "skah slilsiezz",
      "kror rurr",
      "blief grakkoenks",
      "bert-bert squnt",
      "froef-froef shullown",
      "paff-paff shels",
      "wakfec grifa",
      "crebbass tril",
      "naubboow trondierr",
    ],
  },
  Hutt: {
    name: "Hutt",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-hutt-names.php",
    defaultNonBinaryNames: [
      "niddlo tenjed",
      "mambu gish",
      "sawnu sparloz",
      "gerka fihl",
      "braddlish smashain",
      "bwono bard",
      "tillob yachre",
      "giffiwu praiz",
      "shegrishell kastib",
      "boojaabug proh",
    ],
  },
  Iktotchi: {
    name: "Iktotchi",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-iktotchi-names.php",
    defaultFemaleNames: [
      "tumkij vemin",
      "zishi dis",
      "torne vehaan",
      "furur tar",
      "tifna chizu",
      "farli kaal",
      "nunkon haadamm",
      "kifloj zemm",
      "caron chafel",
      "comnon vos",
    ],
    defaultMaleNames: [
      "niflaer hedimm",
      "seldam namm",
      "halde defas",
      "cilva chal",
      "nofur toda",
      "dumraej du",
      "zulmon kejiin",
      "wushkeij kiir",
      "canvij nafas",
      "mifyi jimm",
    ],
  },
  "Ishi Tib": {
    name: "Ishi Tib",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-ishi-tib-names.php",
    defaultFemaleNames: [
      "onzas hul",
      "sihre drambow",
      "voprem lin",
      "iklyen anduc",
      "pholga baw",
      "almof drargim",
      "enlianter zil",
      "seghesmim laebirr",
      "emziekhon brutz",
      "hineffeth draelziff",
    ],
    defaultMaleNames: [
      "shel tun",
      "ciam slaalraal",
      "shech letz",
      "tund zimzaff",
      "rumluch nong",
      "tagrog tikzuw",
      "jubleet ruff",
      "shartemrind vunre",
      "shurnanrurc cael",
      "henlomich vorgom",
    ],
  },
  Ithorian: {
    name: "Ithorian",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-ithorian-names.php",
    defaultFemaleNames: [
      "vle sokill",
      "ma slowowethh",
      "vhees chooso",
      "khys tat",
      "bhywshyl eblum",
      "cwohhamm sitrohol",
      "pwiwhah dirtan",
      "kluuwlyrmaf noolendi",
      "nenforher frootim",
      "swydwalsoh lurlq",
    ],
    defaultMaleNames: [
      "je tofe",
      "leth viweddod",
      "qerr pwaqed",
      "dac frill",
      "houxxurr buflig",
      "feemfarn indebblok",
      "onciwl verek",
      "libbumfew nivulirlq",
      "jwissomleerd turid",
      "phuuwbonuut lits",
    ],
  },
  Jawa: {
    name: "Jawa",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-jawa-names.php",
    defaultFemaleNames: [
      "olok walin",
      "voerek b'iacicic",
      "kebud klamuz",
      "ona dol",
      "nipu qusekth",
      "luiteec b'adinokt",
      "klavaneom edal",
      "bivusem timoejuc",
      "sloesamis kkiqihs",
      "slawemec m'ik",
    ],
    defaultMaleNames: [
      "pridt mehi",
      "bliw nkusihe",
      "jo lelian",
      "tag piy",
      "vunipp tleves",
      "hitjeen d'nelakak",
      "ziibwut tlovoc",
      "jithchazo k'agorikth",
      "mungithchin eliz",
      "kleblattunt sud",
    ],
  },
  Kaleesh: {
    name: "Kaleesh",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-kaleesh-names.php",
    defaultFemaleNames: [
      "dulo qannar",
      "zoddi san grer",
      "teva buth",
      "rome byrre",
      "buldu kus",
      "ddungosu skazzossh",
      "lmendoma bonnel",
      "glumkule toggo",
      "gnezoro jal tash",
      "ddolmalu juddan",
    ],
    defaultMaleNames: [
      "grosh begge",
      "kissh qaggo",
      "bil qeer",
      "meckash bualleish",
      "santigh tees",
      "qassil san qyl",
      "nymtyr skudas",
      "belraeron qako",
      "aakkohirg kozer",
      "tykriragh symmei",
    ],
  },
  Kaminoan: {
    name: "Kaminoan",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-kaminoan-names.php",
    defaultFemaleNames: [
      "ha brai",
      "yim buvo",
      "mi dir",
      "go wolraa",
      "seh girti",
      "lolma bu",
      "heawi deroo",
      "kaiwi bavu",
      "toma bridrui",
      "yilna mur",
    ],
    defaultMaleNames: [
      "kam tu",
      "kleac kirluo",
      "pal to",
      "klam sadris",
      "naa dilos",
      "vorum daidrai",
      "lavam malmi",
      "pema wosaa",
      "vamo drisii",
      "derul brolriru",
    ],
  },
  "Kel Dor": {
    name: "Kel Dor",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-kel-dor-names.php",
    defaultFemaleNames: [
      "cha brani",
      "ha gotchesza",
      "chees tlisoc",
      "si dis",
      "arreen draci",
      "ves'u numnuuro",
      "ghus'il aatoln",
      "roqee'reeth bokraga",
      "hu'hi'ru echazz",
      "parra'ci paln",
    ],
    defaultMaleNames: [
      "charss shanuc",
      "din achokun",
      "jer drocang",
      "naa yun",
      "hy diszas",
      "jocyr zilrusa",
      "wot'ea drurre",
      "dor'alt bastekan",
      "jyc'a taszak",
      "ol'ar ges",
    ],
  },
  Keshiri: {
    name: "Keshiri",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-keshiri-names.php",
    defaultFemaleNames: [
      "arni dildezh",
      "uzi gunna",
      "sezse vur",
      "kerra uld",
      "arne vurneld",
      "sirre illan",
      "erni das",
      "sazsa kild",
      "lehe kuttax",
      "jirva holar",
    ],
    defaultMaleNames: [
      "zhat shornuld",
      "zahre woldex",
      "iazek guzh",
      "tsurzagg shirnor",
      "jastar thar",
      "arzet wi",
      "zha irras",
      "zam vattur",
      "gartin ulnax",
      "jirjonn voold",
    ],
  },
  Kiffar: {
    name: "Kiffar",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-kiffar-names.php",
    defaultFemaleNames: [
      "unta kexlax",
      "sairi karrizit",
      "vimles zeszas",
      "yimlis mon",
      "serre tel",
      "brairves garekat",
      "zali nezzux",
      "yumel moxril",
      "tile vos",
      "ven zezzix",
    ],
    defaultMaleNames: [
      "shanlor kex",
      "quvos dolakev",
      "vatas nerletan",
      "mutosin met",
      "qethir kel",
      "zathrorol kestizen",
      "shune nex",
      "muinla razev",
      "pegos des",
      "zotalas zostex",
    ],
  },
  Klatooinian: {
    name: "Klatooinian",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-klatooinian-names.php",
    defaultFemaleNames: [
      "kit grovai",
      "duh kig",
      "kex daba",
      "mishi teeg",
      "adix agtig",
      "edaz zik",
      "doalut slipraci",
      "vinumli brirria",
      "comukri ugailli",
      "vesakacs bagtieni",
    ],
    defaultMaleNames: [
      "viba fozall",
      "vebyil d'rill",
      "iros jill",
      "ontuk nibane",
      "darobar groc",
      "hurduzer iervaa",
      "indarick larrall",
      "obyilat zervira",
      "gommekut jupdu",
      "ontucir jok",
    ],
  },
  Korunnai: {
    name: "Korunnai",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-korunnai-names.php",
    defaultFemaleNames: [
      "novo higdom",
      "wemmo gango",
      "toffa wamvo",
      "shathea travdo",
      "taesi gotvi",
      "dolu trismu",
      "lisi dupnom",
      "dume thasse",
      "zuso monto",
      "zeho sidlul",
    ],
    defaultMaleNames: [
      "brur sofno",
      "gac vopta",
      "zioth numle",
      "tul thovnes",
      "vek thamno",
      "innu domnul",
      "rolle noggim",
      "iorre wogdam",
      "lennoun trolno",
      "oguth vunvo",
    ],
  },
  Kubaz: {
    name: "Kubaz",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-kubaz-names.php",
    defaultFemaleNames: [
      "vugis kegrin",
      "selnol co",
      "dirbif rurlam",
      "mubem vham",
      "relne ludson",
      "shabom r'loksam",
      "calni ru",
      "shanlo rubza",
      "larol vorlu",
      "fazris nok",
    ],
    defaultMaleNames: [
      "rbaf vonak",
      "shnen rairlam",
      "lurg vhaka",
      "deolda kherlas",
      "ugra rudzo",
      "nduzenk lalvok",
      "kealden vhako",
      "urgetan fupum",
      "kevloro f'laz",
      "levranol feabzu",
    ],
  },
  Lasat: {
    name: "Lasat",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-lasat-names.php",
    defaultFemaleNames: [
      "riza ganonniet",
      "nata domet",
      "kola net",
      "jadi virredd",
      "juzo krazeagg",
      "chavazu klon",
      "kulava vonnevat",
      "ganute drelledd",
      "javazi got",
      "gazise gadd",
    ],
    defaultMaleNames: [
      "vrit krellemmog",
      "rad kogan",
      "drad ran",
      "zaddid vannezad",
      "roklan tragg",
      "giggib avelon",
      "divit drin",
      "zuglonit ralonedd",
      "gorivib drott",
      "duglulin alleb",
    ],
  },
  Lothalite: {
    name: "Lothalite",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-lothalite-names.php",
    defaultFemaleNames: [
      "yoddit krong",
      "dimne khuamu",
      "azhine tranzuzeng",
      "vozede drittek",
      "hoddada sendag",
      "yireihnde khoshtid",
      "varash sildirri",
      "veshei zak",
      "danreez sundeg",
      "birash sushtik",
    ],
    defaultMaleNames: [
      "rebrod ser",
      "onzain edgeng",
      "pobum dhung",
      "pak kruarzalleng",
      "ebif saizad",
      "penzias zolayit",
      "mai fhuadgizut",
      "maf yteyuk",
      "kam inra",
      "nazzuk gar",
    ],
  },
  Mandalorian: {
    name: "Mandalorian",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-mandalorian-names.php",
    defaultFemaleNames: [
      "his shous",
      "hi strorvhai",
      "zhu ruagg",
      "bu crornic",
      "hinnan wihl",
      "zibbi brusounch",
      "bamme kall",
      "whovish qoyol",
      "hibayda moc",
      "zhisserilk voutehl",
    ],
    defaultMaleNames: [
      "wiodth jywr",
      "nan nelbord",
      "choek pell",
      "kraits myso",
      "uscang miwr",
      "krossad qolluungh",
      "azdoe fec",
      "njoyo crorvod",
      "jisagad jygh",
      "sivobok straggard",
    ],
  },
  Mikkian: {
    name: "Mikkian",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-mikkian-names.php",
    defaultFemaleNames: [
      "ravra vesim",
      "vizas mrahi",
      "hipli nmin",
      "zil nes",
      "tavral hisa",
      "haza manal",
      "dir miza",
      "til zehen",
      "teer vim",
      "zevras has",
    ],
  },
  Mirialan: {
    name: "Mirialan",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-mirialan-names.php",
    defaultFemaleNames: [
      "delo fuvenn",
      "thostez'or despolt",
      "ornin ofasaz",
      "canko sifihl",
      "thesle surz",
      "verne payrcins",
      "shastra drir",
      "thuki erz",
      "sarsela hespilt",
      "larse hawol",
    ],
    defaultMaleNames: [
      "ovan weyspeluh",
      "gos panab",
      "ir gormillez",
      "yt khyherill",
      "kin fet",
      "kraboc trekid",
      "mold khawor",
      "fisslas uhaneerz",
      "djot dralet",
      "surat droromurk",
    ],
  },
  "Mon Calamari": {
    name: "Mon Calamari",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-mon-calamari-names.php",
    defaultFemaleNames: [
      "hos wackdoc",
      "sent duhuddixx",
      "deh bingass",
      "shum wixz",
      "hikyi mumdeeb",
      "sinah vraptomgen",
      "bafweent rupi",
      "sehna peeckdolkehd",
      "esakni jooddals",
      "almumbi pac",
    ],
    defaultMaleNames: [
      "graff brahoxz",
      "hoff dokekbuxx",
      "marl hegreehb",
      "chalmarn wia",
      "bulspun sothas",
      "nonerl vrevnigruls",
      "cruukkasz niddosch",
      "chimckuth nebrothria",
      "kricklumbruns kobrails",
      "hiygengarx ghu",
    ],
  },
  Muun: {
    name: "Muun",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-muun-names.php",
    defaultMaleNames: [
      "jot vellok",
      "ur slait",
      "sils kina",
      "movoz liphint",
      "hai tak",
      "nestan vaivuus",
      "tett haith",
      "clirgelalt saphok",
      "gacok pen",
      "bronevo kissen",
    ],
  },
  "Naboo (Human)": {
    name: "Naboo (Human)",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-naboo-names.php",
    defaultFemaleNames: [
      "padelo collaulke",
      "teerré benmer",
      "ishalle cobauss",
      "ceerrelle shulgittas",
      "cende jirraur",
      "tochi ham",
      "lulla kruviallit",
      "dakmolas moborgon",
      "muche fassor",
      "hadi gel",
    ],
    defaultMaleNames: [
      "galosiv jomall",
      "carth graskos",
      "wer ball",
      "zarl klibilkenn",
      "grul brantator",
      "duv hembot",
      "ruk flurvau",
      "deanov nammam",
      "bad mumbor",
      "varmaalom vastelo",
    ],
  },
  Nautolan: {
    name: "Nautolan",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-nautolan-names.php",
    defaultFemaleNames: [
      "hoot goagin",
      "dhas motinnent",
      "pa barja",
      "zif stits",
      "elnu zeervu",
      "wythee uchmosta",
      "shulleah zirrag",
      "athicu surenrimt",
      "pulrimol drervuz",
      "sathofie dree",
    ],
    defaultMaleNames: [
      "rhonn geerdig",
      "wig drorgagrond",
      "coc lude",
      "janroof zi",
      "khorul rhama",
      "coomteynn geddongu",
      "eno ergec",
      "etheatvo vinnorvug",
      "zisnamru gaktess",
      "kenduspred rha",
    ],
  },
  Neimoidian: {
    name: "Neimoidian",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-neimoidian-names.php",
    defaultFemaleNames: [
      "buith ikai",
      "smi srotet",
      "bee rugge",
      "fi etri",
      "blee grofad",
      "hari protfa",
      "sovi gotba",
      "mumma zruifduth",
      "vesu srunkka",
      "zuerra fonva",
    ],
    defaultMaleNames: [
      "git brofur",
      "righ khitoth",
      "yuind kreetrim",
      "jeph gagnud",
      "odmlo kifiy",
      "errull kilvas",
      "othulb egrin",
      "puntuhn baffii",
      "tidrultend zrukki",
      "imoruund srimrai",
    ],
  },
  Nikto: {
    name: "Nikto",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-nikto-names.php",
    defaultNonBinaryNames: [
      "da chash",
      "girsk nindu",
      "haav nec",
      "jukrowl zagrec",
      "jekhawl werch",
      "bhandrosk ubank",
      "eshyngaid qeg",
      "tearydgegg fanko",
      "t'sron'drooddoo jisk",
      "s'voodrik'nov tunturr",
    ],
  },
  Nothoiin: {
    name: "Nothoiin",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-nothoiin-names.php",
    defaultFemaleNames: [
      "ali migo",
      "vatil cozranzu",
      "votho munave",
      "esah hirendod",
      "othe cildrad",
      "alas choltralri",
      "asa rogosnel",
      "oza ordintir",
      "nata hozosru",
      "vaho zirol",
    ],
    defaultMaleNames: [
      "velm vagosa",
      "tchinro rildrirmen",
      "jarlesh nuvrazris",
      "kosvez sasra",
      "uldriz rulaldes",
      "wevlimo volkrad",
      "thovon nyvartin",
      "chegi vylkrol",
      "ru mover",
      "vhesenn ryzan",
    ],
  },
  "Onderonian (Human)": {
    name: "Onderonian (Human)",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-onderonian-names.php",
    defaultFemaleNames: [
      "bemoh rid",
      "idohe ramee",
      "marno tor",
      "leshroanel boph",
      "lanrin ratrosh",
      "homma doph",
      "lalma kunterr",
      "kemma venroph",
      "lanja banradi",
      "lolnonil radrevi",
    ],
    defaultMaleNames: [
      "das joshaph",
      "hommurrum nonrorr",
      "nolvok dotreerr",
      "sar nentee",
      "dak pir",
      "giistus givrish",
      "shivon eti",
      "gas huvi",
      "kandoh vaarveer",
      "shomzar duvrid",
    ],
  },
  Ortolan: {
    name: "Ortolan",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-ortolan-names.php",
    defaultFemaleNames: [
      "silnes hee",
      "meffo babe",
      "wehol ra",
      "lodnan beegol",
      "wabo los",
      "safreth sroqaq",
      "ensos suk",
      "phahham belaq",
      "buphlo rug",
      "natlen raijeq",
    ],
    defaultMaleNames: [
      "tar me",
      "rok saduk",
      "vug dri",
      "teg leneq",
      "hoq le",
      "hindram degaim",
      "rudrax hol",
      "boolom drooteg",
      "dorbij me",
      "berlatz halod",
    ],
  },
  Pantoran: {
    name: "Pantoran",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-pantoran-names.php",
    defaultFemaleNames: [
      "rezzan shulira",
      "theera emo",
      "te hanro",
      "iyona te",
      "eyoni neernok",
      "oya kuli",
      "teji rhichik",
      "shela sumil",
      "chan hu",
      "sonlix choopirrel",
    ],
    defaultMaleNames: [
      "vosed rheti",
      "un uri",
      "fu meekon",
      "ensod nemano",
      "dve imo",
      "esh nimo",
      "omanind rhanro",
      "dimnad hopal",
      "dverrer oonrik",
      "chisond tirnik",
    ],
  },
  "Pau'an": {
    name: "Pau'an",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-pauan-names.php",
    defaultFemaleNames: [
      "lah zal",
      "moy blaret",
      "cies mel",
      "heay zlam",
      "resel zahet",
      "lievem nomeng",
      "rialey tudol",
      "sohas ferey",
      "riohay zlonoll",
      "nalam vlubat",
    ],
    defaultMaleNames: [
      "mor jezel",
      "zun brovod",
      "dal broll",
      "sid vlob",
      "tillam laneng",
      "zedrin keb",
      "tovir vlumull",
      "veoldur verem",
      "teovod glon",
      "vinid klahum",
    ],
  },
  Quarren: {
    name: "Quarren",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-quarren-names.php",
    defaultFemaleNames: [
      "tsik nink",
      "krarg mikkud",
      "sqerr trull",
      "zof chusmiz",
      "jar dod",
      "krolmot sllovisk",
      "chrabeq tim",
      "testhuask tsaqoz",
      "firrhergg virv",
      "nukkilg thiluff",
    ],
    defaultMaleNames: [
      "cisk bisk",
      "dhun yadmeff",
      "borsk will",
      "the lunteeg",
      "gef tra",
      "waulpal krabnad",
      "trilwenn dad",
      "whyllat ninret",
      "phillil squff",
      "galwik koppid",
    ],
  },
  Rodian: {
    name: "Rodian",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-rodian-names.php",
    defaultFemaleNames: [
      "thriph broldee",
      "grii iweaazit",
      "blak xreentahnt",
      "vli mip",
      "slithim geka",
      "vrelkii greejeyero",
      "zmene ewye",
      "cheethlo nyindaldyo",
      "voaflulle yody",
      "ebolwi thoq",
    ],
    defaultMaleNames: [
      "knuull vlakoark",
      "vrix evyoppeht",
      "dhav diaksar",
      "twep trur",
      "ermarm surme",
      "cheefil byinwukcec",
      "blidduu cantuo",
      "snirra prioganki",
      "speewaxu balzo",
      "ceegwithald wee",
    ],
  },
  Savarian: {
    name: "Savarian",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-savarian-names.php",
    defaultFemaleNames: [
      "hamihe zubaziy",
      "phirwohi madu",
      "hemna raldid",
      "phanri cabralin",
      "veze delgugath",
      "lerwi rertu",
      "rarpa rirwijeerd",
      "zolna nalgod",
      "zilna celcay",
      "tiru geboray",
    ],
    defaultMaleNames: [
      "dranwum vepama",
      "myrzar dezrava",
      "shynhorn mazorind",
      "khozrum nizras",
      "rhyngeh bedron",
      "kragran rolgeed",
      "dhomnud nuglanith",
      "redwor vedinot",
      "ghinuln vigrulo",
      "zyrwild burvagon",
    ],
  },
  Selkath: {
    name: "Selkath",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-selkath-names.php",
    defaultFemaleNames: [
      "kewirroks wud",
      "tsaontass bwizri",
      "do genki",
      "johsoshah bwortov",
      "wolte wudmeex",
      "ferta pizcros",
      "chesi crerzi",
      "ezask bwonko",
      "bwoskesess bedran",
      "fur hukrix",
    ],
    defaultMaleNames: [
      "cheks bwertin",
      "duc go",
      "stezceh wao",
      "bwonkess hurcad",
      "fedirvou moth",
      "nawo hescros",
      "feveh ma",
      "soahkaks bisci",
      "shosshir wouh",
      "gusshi wartu",
    ],
  },
  Selonian: {
    name: "Selonian",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-selonian-names.php",
    defaultFemaleNames: [
      "wiil thotte",
      "shits thurr",
      "sha dondos",
      "cecly piaruve",
      "klime bisyal",
      "shravam disden",
      "chicle kel",
      "chakothats fisuvu",
      "seyocni sulesto",
      "sherskami ke",
    ],
    defaultMaleNames: [
      "foz ruwumdom",
      "dov thur",
      "zed fim",
      "ran towore",
      "gek pemo",
      "kahluv dosso",
      "fokar dovente",
      "nuknug komes",
      "quzon re",
      "dehleg kimo",
    ],
  },
  Sephi: {
    name: "Sephi",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-sephi-names.php",
    defaultFemaleNames: [
      "ago tash",
      "aalde minn",
      "vothi nuth",
      "egee jod",
      "yethrea nonn",
      "filka rash",
      "adi jemn",
      "satla mall",
      "veirla noy",
      "tirli roy",
    ],
    defaultMaleNames: [
      "jovex zuhn",
      "zulaavox nenn",
      "agula not",
      "monik feth",
      "vuglinek fad",
      "numraac zohn",
      "vogilo yel",
      "rozos zehn",
      "jomron hoss",
      "ranvux jin",
    ],
  },
  "Serennian (Human)": {
    name: "Serennian (Human)",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-serennian-names.php",
    defaultFemaleNames: [
      "cra mogih",
      "datamo luund",
      "krenza ugde",
      "kridze doss",
      "lezronze vougras",
      "nagneh mah",
      "dildai burm",
      "maimno nam",
      "jeldai dolkis",
      "endelda zikredd",
    ],
    defaultMaleNames: [
      "vilhe dam",
      "gril varn",
      "zalhod uzzeh",
      "uttom buulde",
      "goda loorgem",
      "gelhec andirm",
      "sol band",
      "eros negreh",
      "natti vandar",
      "nec vos",
    ],
  },
  Shistavanen: {
    name: "Shistavanen",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-shistavanen-names.php",
    defaultFemaleNames: [
      "thel bovgat",
      "heash fuk",
      "hoz kraekri",
      "lat val",
      "lel dhaanuc",
      "kunn ful",
      "vec dodan",
      "har droc",
      "vef dhonig",
      "shiev krut",
    ],
    defaultMaleNames: [
      "loor vahro",
      "vad kuvl",
      "blaaq brahraq",
      "logg sav",
      "blos crehxuft",
      "lal dom",
      "radral brokvul",
      "baalraaz son",
      "nekri cekrak",
      "camvod lur",
    ],
  },
  Skakoan: {
    name: "Skakoan",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-skakoan-names.php",
    defaultMaleNames: [
      "halaga lembom",
      "hram tezo",
      "zul lewos",
      "zumb lo",
      "hralla neem",
      "vunt nirnem",
      "dug naval",
      "dag nebrel",
      "zal dreezal",
      "damol trable",
    ],
  },
  Snivvian: {
    name: "Snivvian",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-snivvian-names.php",
    defaultFemaleNames: [
      "anli hak",
      "sursert cal",
      "otrak num",
      "zorlam ziklo",
      "koglitlu mig",
      "garmettli nim",
      "zulkevu titri",
      "ukmollo zok",
      "itroku kutt",
      "vognetli zokpu",
    ],
    defaultMaleNames: [
      "gek mura",
      "yech knagg",
      "werl sott",
      "mun zazra",
      "gegrerl durr",
      "manrerl nonku",
      "yivleek ranga",
      "turlutt digpu",
      "bottem comki",
      "kascich zul",
    ],
  },
  Stormtrooper: {
    name: "Stormtrooper",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-stormtrooper-names.php",
    defaultNonBinaryNames: [
      "JYI-899",
      "CD-749",
      "KGE-733",
      "242",
      "C-958",
      "3630",
      "3354",
      "NK267",
      "VYO996",
      "PXL500",
    ],
  },
  Sullustan: {
    name: "Sullustan",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-sullustan-names.php",
    defaultFemaleNames: [
      "hunn vullibb",
      "ko vhum",
      "frel sweabbi",
      "trashess pum",
      "nebo ghantrirss",
      "lirdu miels",
      "yalmi yolki",
      "omlappel swanr",
      "gelmolnya pinduuk",
      "mufenbe biirs",
    ],
    defaultMaleNames: [
      "zek plirto",
      "dwi miis",
      "frel nryakkim",
      "kuud winn",
      "puu lumiirl",
      "vubuc braanb",
      "diidmyulss tovnu",
      "harkuss ypt",
      "turnibrot bruagnos",
      "habuufrulss al",
    ],
  },
  Talz: {
    name: "Talz",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-talz-names.php",
    defaultFemaleNames: [
      "ruthan vuc",
      "alta wac",
      "nethek rut",
      "cugtu rektec",
      "nithep rum",
      "hortac dut",
      "solmi red",
      "nemdun vum",
      "chimtup nilte",
      "nemlot zun",
    ],
    defaultMaleNames: [
      "me zide",
      "dre guptim",
      "feth runtit",
      "lirsil souptis",
      "gridchon vu weptit",
      "cinven zeptoc",
      "berse douk",
      "unvornak wit",
      "cazrelnu radem",
      "cuszellu dac",
    ],
  },
  Tholothian: {
    name: "Tholothian",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-tholothian-names.php",
    defaultFemaleNames: [
      "ilvit rinn",
      "mynnis sil",
      "ol nazri",
      "ottine annack",
      "etsil gatt",
      "eto cinress",
      "shatall pia",
      "thindoya cavrel",
      "vanosa vi",
      "itsett razzis",
    ],
    defaultMaleNames: [
      "hal cevass",
      "vonirr gecran",
      "harlez piavrir",
      "rolvo nas",
      "monarr yandett",
      "rozmis pozra",
      "celra cerzann",
      "cog standass",
      "hozles innatt",
      "jegriz ya",
    ],
  },
  Togruta: {
    name: "Togruta",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-togruta-names.php",
    defaultFemaleNames: [
      "caumi baass",
      "hilesh jem",
      "vahnen tedrorm",
      "shrurshah jifoza",
      "mutrish valeramm",
      "busori ourkellirm",
      "besh vilrira",
      "zavash adressamm",
      "persha zas",
      "hynresh malloni",
    ],
    defaultMaleNames: [
      "dareemath phodre",
      "merhatish nezli",
      "skeswend nydiri",
      "juktoda nadrarm",
      "sujami vamalib",
      "maldo dawoza",
      "cuhenok baarm",
      "turheesh rawinah",
      "suraand phardosharm",
      "azwud vardal",
    ],
  },
  Toydarian: {
    name: "Toydarian",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-toydarian-names.php",
    defaultFemaleNames: [
      "fappe sim",
      "sorga zusgu",
      "totri lobb",
      "rogli naafaa",
      "qilo rulg",
      "lessona giblu",
      "sanlesu tibb",
      "lilbipi marze",
      "nazize rul",
      "deffergo kegmo",
    ],
    defaultMaleNames: [
      "gug sum",
      "qol nagge",
      "god kelg",
      "nibb pulbu",
      "kasca tulg",
      "drigo ruvu",
      "danu sun",
      "drerfem zaagli",
      "zonanma vaag",
      "berriddun kate",
    ],
  },
  Trandoshan: {
    name: "Trandoshan",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-trandoshan-names.php",
    defaultFemaleNames: [
      "tym egse",
      "tsoo grors",
      "tha zokrassk",
      "mseffonn rut",
      "rhiha ammyt",
      "idwee hses",
      "yphac fecdeasch",
      "greslath gror",
      "mozaff tsakkaa",
      "ghalsot bru",
    ],
    defaultMaleNames: [
      "uss hskarsa",
      "mimx hsosch",
      "duiff iraurn",
      "unk kle",
      "khrussk hssaunlet",
      "irnerrng brugh",
      "krolturr suggoo",
      "rikka hssess",
      "vrondey vlibreosch",
      "drocrarst daasch",
    ],
  },
  "Tusken Raider": {
    name: "Tusken Raider",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-tusken-raider-names.php",
    defaultFemaleNames: [
      "Gr'Rhierk zriqheg",
      "Thork qog",
      "Vom tatak",
      "Yaarh brek",
      "Rim vokdoc",
      "Gekka voqt",
      "Ruxta qenvort",
      "Taqzaa loq",
      "Hode yokhirc",
      "Taxre krak",
    ],
    defaultMaleNames: [
      "Ke trekhat",
      "Zor zrard",
      "Kag hovuk",
      "K'Chacan gard",
      "Vugdec shaqork",
      "Gurur'okrurs",
      "Rurrur'okrs",
      "Krrorr'oaruur",
      "Ogurur'orrr'rrt",
      "Ggk'otrr'rtr",
    ],
  },
  "Twi'lek": {
    name: "Twi'lek",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-twilek-names.php",
    defaultFemaleNames: [
      "timirne kidinn",
      "nolle lertusall",
      "trosdri narus",
      "he'vi brureinn",
      "kethne bo'nuh",
      "lerdah aseek",
      "timun ladrol",
      "othru disseedet",
      "ki du'lit",
      "rerne guda",
    ],
    defaultMaleNames: [
      "mash o'na",
      "jar pi'lot",
      "qwon rodaz",
      "jeroddi bann",
      "goznell emeh",
      "far voles",
      "mehen ley",
      "qweyonn ryz",
      "jotan koss",
      "pretrath chat",
    ],
  },
  Ugnaughts: {
    name: "Ugnaughts",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-ugnaught-names.php",
    defaultFemaleNames: [
      "zaclek gnuggo",
      "romcoll mokk",
      "zogmodl gnigi",
      "klemladl kugro",
      "klenkilli snuka",
      "vulnoru gnozko",
      "ugrava sniggi",
      "dulsima zur",
      "zunlotlo knuklu",
      "kogmatlu nok",
    ],
    defaultMaleNames: [
      "zax natt",
      "woorl snorni",
      "drich tutt",
      "mel run",
      "bakurn dan",
      "yoonur zatro",
      "wakkim magna",
      "toogru sogpa",
      "woivlia guvku",
      "garlearn kuc",
    ],
  },
  Weequay: {
    name: "Weequay",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-weequay-names.php",
    defaultFemaleNames: [
      "riir klutimz",
      "xoz sac",
      "vax khabgomz",
      "bees sak",
      "foc veikror",
      "gecna daud",
      "pummik utrik",
      "pakmi gru",
      "teerkax gegun",
      "vicreh fux",
    ],
    defaultMaleNames: [
      "truwn svokkad",
      "eert frord",
      "qo khistay",
      "chek frusk",
      "cas-buy bremtunz",
      "krob-do tic",
      "la-me leidrosh",
      "yos-lanm-ba sulc",
      "gunnud-za fitrig",
      "tonduk-ro drog",
    ],
  },
  Wookiee: {
    name: "Wookiee",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-wookiee-names.php",
    defaultFemaleNames: [
      "wranma",
      "nerceu",
      "rruarrsirr",
      "bubbaall",
      "drieraaaso",
      "ghrukaaachan",
      "dhunnulgosh",
      "cabhibeuklook",
      "kuhbelrivo",
      "whoovittuvy",
    ],
    defaultMaleNames: [
      "drayl",
      "snrrahr",
      "byyythiyykk",
      "haewhhriyan",
      "vrathridrr",
      "snrinhitti",
      "gworwwonninch",
      "uwrrordrorr",
      "hriaanchurwwamme",
      "snrleeorcardrywrrhuark",
    ],
  },
  Yarkora: {
    name: "Yarkora",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-yarkora-names.php",
    defaultFemaleNames: [
      "lezith hige",
      "shezis mellat",
      "chefys dhelatch",
      "fevi semith",
      "lemec vinatch",
      "cefel fanish",
      "lerin tekach",
      "hidas zhaza",
      "shelen merash",
      "sheve chilled",
    ],
    defaultMaleNames: [
      "drird hire",
      "shur cilem",
      "chim dasa",
      "vryder cidesh",
      "hyrard dheme",
      "vhillalk hasa",
      "whimelk-dreball came",
      "thymae-whelalk chegit",
      "hallal-bene vaca",
      "dazel-gryne heketh",
    ],
  },
  Zabrak: {
    name: "Zabrak",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-zabrak-names.php",
    defaultFemaleNames: [
      "ildra amu",
      "trokkosah bhov",
      "soran nuzac",
      "sin midiner",
      "rhilvo kag",
      "oz krent",
      "runotez ech",
      "uh seev",
      "ri xec",
      "dre bharl",
    ],
    defaultMaleNames: [
      "vurralirth tor",
      "graorra dorr",
      "haag uvasach",
      "dhul gant",
      "chig gedeth",
      "fredeg xaozrizis",
      "janir bhamrol",
      "gesh zev",
      "aith hazroc",
      "thisith liven",
    ],
  },
  Zeltron: {
    name: "Zeltron",
    generatorUrl: "https://www.fantasynamegenerators.com/sw-zeltron-names.php",
    defaultFemaleNames: [
      "irnyr andoder",
      "zizhace raanzari",
      "efo rezrozil",
      "lefrosu wata",
      "sofri bace",
      "iasy remall",
      "enrylur zedroll",
      "ryfry tazlo",
      "iashu pacarock",
      "ianlo ylze",
    ],
    defaultMaleNames: [
      "ventod tonozod",
      "erruhb pycozor",
      "nar pelveron",
      "hahs torvalonn",
      "mallorc welza",
      "vedrehn tesann",
      "jinne benzezor",
      "klarruhb azlas",
      "mag razer",
      "zennihn wanzar",
    ],
  },
  Zygerrian: {
    name: "Zygerrian",
    generatorUrl:
      "https://www.fantasynamegenerators.com/sw-zygerrian-names.php",
    defaultFemaleNames: [
      "yozes gisagal",
      "ireth krildoll",
      "osoj crena",
      "alath kac",
      "hinall grel",
      "tisem armall",
      "nidoll medro",
      "nall krasral",
      "noss nadame",
      "osoh cres",
    ],
    defaultMaleNames: [
      "slom endo",
      "agsis crasen",
      "noke mill",
      "atirts cril",
      "scorde sena",
      "arerts tizo",
      "scorzavis trarnakil",
      "ramart kollo",
      "erard crirnaged",
      "daagrik crolnod",
    ],
  },
  Droid: {
    name: "Droid",
    generatorUrl: "",
    defaultFemaleNames: [
      "Q9-X7",
      "L4-T0",
      "Z3-RN",
      "R1-K5",
      "B7-M9",
      "TQ-3L",
      "D0-R8",
      "X2-VN",
      "M5-K0",
      "J9-C4",
    ],
    defaultMaleNames: [
      "Sparky",
      "Glitch",
      "Whistler",
      "Clank",
      "Zee",
      "Sprocket",
      "Rusty",
      "Vox",
      "Buzz",
      "Nibs",
    ],
  },
};

const SPECIES_LIST: { id: string; label: string }[] = Object.keys(SPECIES).map(
  (key) => ({
    id: key,
    label: SPECIES[key].name,
  })
);

const DEFAULT_SPECIES = { id: "random", label: "Random" };

//This adds the special random species that randomly selects another species
SPECIES_LIST.unshift(DEFAULT_SPECIES);

export { Species, SPECIES, SPECIES_LIST, DEFAULT_SPECIES };
