const TERRESTRIAL_VEHICLE_TEMPLATES = [
  {
    id: window.crypto.randomUUID(),
    name: "Sandcrawler",
    description:
      "A sandcrawler is a massive, slow-moving transport vehicle used by the Jawas to search the deserts for scrap metal and droid parts. With its towering, tank-like structure and large treaded wheels, it is equipped to carry a vast amount of cargo and can house droids for sale or trade.",
    model: "Sandcrawler",
    modules: [
      {
        id: window.crypto.randomUUID(),
        name: "Engine",
        cost: 0,
        description: "The engine allows the vehicle to move.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Cockpit",
        cost: 0,
        description: "The cockpit allows the vehicle to be driven.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Wide Treads",
        cost: "0",
        description:
          "These wide treads prevent the sandcrawler from sinking into the shifting dunes, at the cost of any maneuverability.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "Maneuverability",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Heavy Hull",
        cost: "1",
        description:
          "The heavy construction of the sandcrawler keeps it safe from dangers out in the dunes at the cost of any impression of speed.",
        destroyed: false,
        increasedSpec: "Durability",
        decreasedSpec: "Speed",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Scrap Workshop",
        cost: "1",
        description:
          "This scrap workshop is where the Jawas strip parts and cobble together sale goods.",
        destroyed: false,
        increasedSpec: "Systems",
        decreasedSpec: "Speed",
      },
    ],
    cargo: [],
    class: "Terrestrial Vehicle",
    maxVp: 4,
    vpSpentOnRepairs: 0,
  },
  {
    id: window.crypto.randomUUID(),
    name: "T-16 Skyhopper",
    description:
      "The T-16 Skyhopper is a small, single-pilot repulsorlift vehicle designed for sport and training, often used for target practice and recreational flying. Known for its speed and maneuverability, it features a sleek design and is occasionally equipped with laser cannons, making it a popular choice for young pilots in the Outer Rim.",
    model: "T-16 Skyhopper",
    modules: [
      {
        id: window.crypto.randomUUID(),
        name: "Engine",
        cost: 0,
        description: "The engine allows the vehicle to move.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Cockpit",
        cost: 0,
        description: "The cockpit allows the vehicle to be driven.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Improved Repulsor",
        cost: "1",
        description:
          "The speed of the T-16 is one of its main draws, particularly for younger pilots.",
        destroyed: false,
        increasedSpec: "Speed",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Reaction Jets",
        cost: "1",
        description:
          "Enhancing the standard control surfaces of the T-16 is a set of reaction jets to improve the maneuverability of the craft.",
        destroyed: false,
        increasedSpec: "Maneuverability",
        decreasedSpec: "",
      },
    ],
    cargo: [],
    class: "Terrestrial Vehicle",
    maxVp: 4,
    vpSpentOnRepairs: 0,
  },
  {
    id: window.crypto.randomUUID(),
    name: "T-47",
    description:
      "The T-47 is a modified transport vehicle originally used for cargo hauling, later repurposed by the Rebel Alliance as a heavy-duty combat airspeeder. After being upgraded with blasters and reinforced for combat, it became a versatile and agile craft used in both ground and air assaults.",
    model: "T-47",
    modules: [
      {
        id: window.crypto.randomUUID(),
        name: "Engine",
        cost: 0,
        description: "The engine allows the vehicle to move",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Cockpit",
        cost: 0,
        description: "The cockpit allows the vehicle to be driven",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Harpoon Gun",
        cost: "1",
        description:
          "The rear gunner on a T-47 has access to a harpoon gun and associated winch.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Blaster Cannons",
        cost: "1",
        description:
          "These front-mounted blaster cannons are a retrofit, but still pack a hefty punch.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Sturdy Frame",
        cost: "1",
        description:
          "The mundane origin of the T-47 belies the strength of the underlying airframe.",
        destroyed: false,
        increasedSpec: "Durability",
        decreasedSpec: "",
      },
    ],
    cargo: [],
    class: "Terrestrial Vehicle",
    maxVp: 4,
    vpSpentOnRepairs: 0,
  },
  {
    id: window.crypto.randomUUID(),
    name: "T3-B",
    description:
      "The T3-B is a medium-class, repulsorlift-powered tank originally used by the Separatists during the Clone Wars. With its missile racks and powerful blasters, it is designed for frontline combat, providing extreme offensive capabilities in ground assaults.",
    model: "T3-B",
    modules: [
      {
        id: window.crypto.randomUUID(),
        name: "Engine",
        cost: 0,
        description: "The engine allows the vehicle to move.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Cockpit",
        cost: 0,
        description: "The cockpit allows the vehicle to be driven.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Linked Blaster Cannons",
        cost: "1",
        description:
          "These linked blaster cannons provide powerful direct-fire support.",
        destroyed: false,
        increasedSpec: "Firepower",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Missile Racks",
        cost: "2",
        description:
          "These missile racks provide an indirect-fire option as well as a massed-fire option to the T3-B's gunner.",
        destroyed: false,
        increasedSpec: "Firepower",
        decreasedSpec: "",
      },
    ],
    cargo: [],
    class: "Terrestrial Vehicle",
    maxVp: 4,
    vpSpentOnRepairs: 0,
  },
  {
    id: window.crypto.randomUUID(),
    name: "Juggernaut",
    description:
      "A Juggernaut is a massive, heavily armored, wheeled transport vehicle used for troop movement and heavy artillery deployment. With its rugged design and immense size, it can carry large amounts of personnel and equipment while providing substantial firepower and protection in battle.",
    model: "Juggernaut",
    modules: [
      {
        id: window.crypto.randomUUID(),
        name: "Engine",
        cost: 0,
        description: "The engine allows the vehicle to move.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Cockpit",
        cost: 0,
        description: "The cockpit allows the vehicle to be driven.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Troop Bay",
        cost: "1",
        description:
          "The Juggernaut can disgorge up to two full squads of soldiers from its troop bay.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Wheeled Carrier",
        cost: "1",
        description:
          "Using wheels instead of walking means the Juggernaut can reach higher speeds over even ground, but struggles when the going gets tough.",
        destroyed: false,
        increasedSpec: "Speed",
        decreasedSpec: "Maneuverability",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Heavy Armor",
        cost: "1",
        description: "The Juggernaut is covered in heavy armor plating.",
        destroyed: false,
        increasedSpec: "Durability",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Auxiliary Weaponry",
        cost: "1",
        description:
          "Lacking a dedicated main weapon, the Juggernaut is still quite capable of fending off infantry with it's auxiliary armament.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
    ],
    cargo: [],
    class: "Terrestrial Vehicle",
    maxVp: 4,
    vpSpentOnRepairs: 0,
  },
  {
    id: window.crypto.randomUUID(),
    name: "AT-TE",
    description:
      "An AT-TE (All Terrain Tactical Enforcer) is a six-legged, heavily armored transport and assault vehicle originally used by the Galactic Republic. Equipped with powerful blasters and capable of carrying troops and heavy artillery, it is designed for both offense and defense in large-scale ground battles.",
    model: "AT-TE",
    modules: [
      {
        id: window.crypto.randomUUID(),
        name: "Engine",
        cost: 0,
        description: "The engine allows the vehicle to move.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Cockpit",
        cost: 0,
        description: "The cockpit allows the vehicle to be driven.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Heavy Hull",
        cost: "1",
        description:
          "The sturdy construction of this vehicle makes it more durable at the cost of speed.",
        destroyed: false,
        increasedSpec: "Durability",
        decreasedSpec: "Speed",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Troop Bay",
        cost: "1",
        description:
          "The AT-TE can disgorge up to a full squad of soldiers from its troop bay.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Main Cannon",
        cost: "1",
        description:
          "The main turret of the AT-TE is armed with a large-bore laser for devastating firepower.",
        destroyed: false,
        increasedSpec: "Firepower",
        decreasedSpec: "",
      },
    ],
    cargo: [],
    class: "Terrestrial Vehicle",
    maxVp: 4,
    vpSpentOnRepairs: 0,
  },
  {
    id: window.crypto.randomUUID(),
    name: "AAT",
    description:
      "An AAT (Armored Assault Tank) is a heavily armored, repulsorlift-equipped combat vehicle used primarily by droid armies. With its powerful blasters and sturdy design, it is capable of providing both offensive firepower and protection during ground assaults.",
    model: "AAT",
    modules: [
      {
        id: window.crypto.randomUUID(),
        name: "Engine",
        cost: 0,
        description: "The engine allows the vehicle to move.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Cockpit",
        cost: 0,
        description: "The cockpit allows the vehicle to be driven.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Heavy Hull",
        cost: "1",
        description:
          "The sturdy construction of this vehicle makes it more durable at the cost of speed.",
        destroyed: false,
        increasedSpec: "Durability",
        decreasedSpec: "Speed",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Main Cannon",
        cost: "1",
        description:
          "The main turret of the AAT is armed with a large-bore laser for devastating firepower.",
        destroyed: false,
        increasedSpec: "Firepower",
        decreasedSpec: "",
      },
    ],
    cargo: [],
    class: "Terrestrial Vehicle",
    maxVp: 4,
    vpSpentOnRepairs: 0,
  },
  {
    id: window.crypto.randomUUID(),
    name: "AT-ST",
    description:
      "An AT-ST (All Terrain Scout Transport) is a smaller, two-legged combat walker used for reconnaissance and support in battle. Agile and equipped with heavy weaponry, it is designed for quick maneuvers in both urban and rugged terrains, offering firepower and mobility in support of larger forces.",
    model: "AT-ST",
    modules: [
      {
        id: window.crypto.randomUUID(),
        name: "Engine",
        cost: 0,
        description: "The engine allows the vehicle to move.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Cockpit",
        cost: 0,
        description: "The cockpit allows the vehicle to be driven.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Bipedal Legs",
        cost: "1",
        description: "Long legs allow the AT-ST to cover ground quickly.",
        destroyed: false,
        increasedSpec: "Speed",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Recon Sensors",
        cost: "1",
        description:
          "The sensor package on the AT-ST is high-quality to aid in its scouting duties.",
        destroyed: false,
        increasedSpec: "Systems",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Side-mount Lasers",
        cost: "1",
        description: "The AT-ST has side-mounted light lasers.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
    ],
    cargo: [],
    class: "Terrestrial Vehicle",
    maxVp: 4,
    vpSpentOnRepairs: 0,
  },
  {
    id: window.crypto.randomUUID(),
    name: "AT-AT",
    description:
      "An AT-AT (All Terrain Armored Transport) is a massive, four-legged walking tank used for heavy assault and troop transport. With its formidable firepower and thick armor, it is designed to traverse rough landscapes and dominate battlefields, often deployed in large numbers during ground conflicts.",
    model: "AT-AT",
    modules: [
      {
        id: window.crypto.randomUUID(),
        name: "Engine",
        cost: 0,
        description: "The engine allows the vehicle to move.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Cockpit",
        cost: 0,
        description: "The cockpit allows the vehicle to be driven.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Heavy Hull",
        cost: "1",
        description:
          "The sturdy construction of this vehicle makes it more durable at the cost of speed.",
        destroyed: false,
        increasedSpec: "Durability",
        decreasedSpec: "Speed",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Chin Lasers",
        cost: "1",
        description:
          "These chin-mounted lasers are ready to blast anything to pieces.",
        destroyed: false,
        increasedSpec: "Firepower",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Troop Bay",
        cost: "1",
        description:
          "The AT-AT can disgorge up to two full squads of soldiers from its troop bay.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Armor Plating",
        cost: "2",
        description:
          "The armor plating that covers important surfaces on the AT-AT is almost impossible to pierce.",
        destroyed: false,
        increasedSpec: "Durability",
        decreasedSpec: "",
      },
    ],
    cargo: [],
    class: "Terrestrial Vehicle",
    maxVp: 5,
    vpSpentOnRepairs: 0,
  },
  {
    id: window.crypto.randomUUID(),
    name: "Skiff",
    description:
      "A skiff is a small, flat-bottomed transport vessel, typically used for quick movement across long distances. Often lightweight and equipped with repulsorlift technology, it is designed for independent operations and can carry a small crew or cargo over difficult terrain.",
    model: "Skiff",
    modules: [
      {
        id: window.crypto.randomUUID(),
        name: "Engine",
        cost: 0,
        description: "The engine allows the vehicle to move.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Cockpit",
        cost: 0,
        description: "The cockpit allows the vehicle to be driven.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Sturdy Hull",
        cost: "1",
        description: "This skiff is well constructed and maintained.",
        destroyed: false,
        increasedSpec: "Durability",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Job-Specific Module",
        cost: "1",
        description:
          "This module does something specific and should be added when this skiff is created.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
    ],
    cargo: [],
    class: "Terrestrial Vehicle",
    maxVp: 4,
    vpSpentOnRepairs: 0,
  },
  {
    id: window.crypto.randomUUID(),
    name: "Hovertank",
    description:
      "A hovertank is a heavily armored, ground-based combat vehicle that uses repulsorlift technology to float above the surface, allowing it to move swiftly across various terrains. Armed with powerful weapons, it is designed for both offensive and defensive operations in battle, offering mobility and firepower in hostile environments.",
    model: "Hovertank",
    modules: [
      {
        id: window.crypto.randomUUID(),
        name: "Engine",
        cost: 0,
        description: "The engine allows the vehicle to move.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Cockpit",
        cost: 0,
        description: "The cockpit allows the vehicle to be driven.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Heavy Hull",
        cost: "1",
        description:
          "The sturdy construction of this vehicle makes it more durable at the cost of speed.",
        destroyed: false,
        increasedSpec: "Durability",
        decreasedSpec: "Speed",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Main Cannon",
        cost: "1",
        description:
          "The main turret of the hovertank is armed with a large-bore laser for devastating firepower.",
        destroyed: false,
        increasedSpec: "Firepower",
        decreasedSpec: "",
      },
    ],
    cargo: [],
    class: "Terrestrial Vehicle",
    maxVp: 4,
    vpSpentOnRepairs: 0,
  },
  {
    id: window.crypto.randomUUID(),
    name: "Podracer",
    description:
      "A podracer is a high-speed, open-air vehicle used in dangerous races, consisting of a cockpit linked to two large engines. Known for its extreme speed and unstable nature, it requires incredible skill to control, making it a thrilling yet perilous racing machine.",
    model: "Podracer",
    modules: [
      {
        id: window.crypto.randomUUID(),
        name: "Engine",
        cost: 0,
        description: "The engine allows the vehicle to move.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Cockpit",
        cost: 0,
        description: "The cockpit allows the vehicle to be driven.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Streamlined Cockpit",
        cost: "1",
        description:
          "This streamlined cockpit allows the podracer to cut through the air effortlessly.",
        destroyed: false,
        increasedSpec: "Speed",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Redlined Engines",
        cost: "1",
        description:
          "The engines on the podracer are tuned for maximum performance, at the cost of some durability.",
        destroyed: false,
        increasedSpec: "Speed",
        decreasedSpec: "Durability",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Racing Thrusters",
        cost: "1",
        description:
          "These thrusters allow the podracer to turn on a tenth-cred. They tend to be pretty tempermental at the best of times though.",
        destroyed: false,
        increasedSpec: "Maneuverability",
        decreasedSpec: "Durability",
      },
    ],
    cargo: [],
    class: "Terrestrial Vehicle",
    maxVp: 4,
    vpSpentOnRepairs: 0,
  },
  {
    id: window.crypto.randomUUID(),
    name: "Sail Barge",
    description:
      "A sail barge is a large, slow-moving vessel designed for transport and combat, often used to traverse harsh, open environments. With its massive sail and sturdy construction, it can serve as a mobile base, equipped with heavy weaponry and a lavish, opulent deck for its occupants.",
    model: "Sail Barge",
    modules: [
      {
        id: window.crypto.randomUUID(),
        name: "Engine",
        cost: 0,
        description: "The engine allows the vehicle to move.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Cockpit",
        cost: 0,
        description: "The cockpit allows the vehicle to be driven.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Luxury Quarters",
        cost: "1",
        description:
          "The owners of this sail barge have installed lavish quarters, granting them a +1 to Charm checks made aboard.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Heavy Hull",
        cost: "1",
        description:
          "The sturdy construction of this vehicle makes it more durable at the cost of speed.",
        destroyed: false,
        increasedSpec: "Durability",
        decreasedSpec: "Speed",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Deck Cannons",
        cost: "1",
        description:
          "The heavy broadside of deck-mounted laser cannons allows this vehicle to pour laser fire on any attacker.",
        destroyed: false,
        increasedSpec: "Firepower",
        decreasedSpec: "",
      },
    ],
    cargo: [],
    class: "Terrestrial Vehicle",
    maxVp: 4,
    vpSpentOnRepairs: 0,
  },
  {
    id: window.crypto.randomUUID(),
    name: "Landspeeder",
    description:
      "A landspeeder is a ground-based vehicle designed for fast travel across various terrains, often featuring a sleek, streamlined design. Powered by repulsorlift technology, it hovers just above the surface, allowing for smooth navigation over uneven landscapes.",
    model: "Landspeeder",
    modules: [
      {
        id: window.crypto.randomUUID(),
        name: "Engine",
        cost: 0,
        description: "The engine allows the vehicle to move.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Cockpit",
        cost: 0,
        description: "The cockpit allows the vehicle to be driven.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Sturdy Hull",
        cost: "1",
        description:
          "The sturdy construction of this landspeeder makes it more durable.",
        destroyed: false,
        increasedSpec: "Durability",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Improved X",
        cost: "1",
        description: "Improve one of this vehicle's stats after it is created.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
    ],
    cargo: [],
    class: "Terrestrial Vehicle",
    maxVp: 4,
    vpSpentOnRepairs: 0,
  },
  {
    id: window.crypto.randomUUID(),
    name: "Airspeeder",
    description:
      "An airspeeder is a versatile, hovercraft-like vehicle designed for high-speed flight, typically used for both transportation and combat. Equipped with advanced repulsorlift technology, these vehicles can navigate urban landscapes or open skies, making them a popular choice among both law enforcement and military forces.",
    model: "Airspeeder",
    modules: [
      {
        id: window.crypto.randomUUID(),
        name: "Engine",
        cost: 0,
        description: "The engine allows the vehicle to move.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Cockpit",
        cost: 0,
        description: "The cockpit allows the vehicle to be driven.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Sturdy Hull",
        cost: "1",
        description:
          "The sturdy construction of this airspeeder makes it more durable.",
        destroyed: false,
        increasedSpec: "Durability",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Improved X",
        cost: "1",
        description:
          "\tImprove one of this vehicle's stats after it is created.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
    ],
    cargo: [],
    class: "Terrestrial Vehicle",
    maxVp: 4,
    vpSpentOnRepairs: 0,
  },
  {
    id: window.crypto.randomUUID(),
    name: "Swoop Bike",
    description:
      "A swoop bike is a high-speed, one-person speeder designed for fast, agile travel across rough terrains. Often used by criminals and racers, these sleek, open-frame vehicles are powered by a repulsorlift engine, making them perfect for rapid escapes or thrilling races.",
    model: "Swoop Bike",
    modules: [
      {
        id: window.crypto.randomUUID(),
        name: "Engine",
        cost: 0,
        description: "The engine allows the vehicle to move.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Cockpit",
        cost: 0,
        description: "The cockpit allows the vehicle to be driven.",
        destroyed: false,
        increasedSpec: "",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Enhanced Engines",
        cost: "1",
        description:
          "These powerful engines allow the swoop bike to achieve incredible speeds.",
        destroyed: false,
        increasedSpec: "Speed",
        decreasedSpec: "",
      },
      {
        id: window.crypto.randomUUID(),
        name: "Turbocharged Repulsor",
        cost: "2",
        description:
          "By turbocharging the repulsor engine, the swoop can achieve truly tremendous speed at the cost of some reliability.",
        destroyed: false,
        increasedSpec: "Speed",
        decreasedSpec: "Durability",
      },
    ],
    cargo: [],
    class: "Terrestrial Vehicle",
    maxVp: 4,
    vpSpentOnRepairs: 0,
  },
];

export { TERRESTRIAL_VEHICLE_TEMPLATES };
